### ISSUE TITLE
ip_napt_enable typo? (IDFGH-9728)

### ISSUE THREAD

**Issue by A6GH** [espressif/esp-lwip#52]
While going through some lwip code, I've come across this line:
https://github.com/espressif/esp-lwip/blob/d5e56d06658ae11292be1baea56204f7120b6fa7/src/core/ipv4/ip4_napt.c#L185

Shouldn't the if condition check if napt_in_any_netif is true, rather than false, and then proceed with disabling napt if the condition is met?

**Comment by david-cermak** [comment]
I think the original intention here was to disable `napt` *globally* only if there no `netif` with `napt` still **ON**.
But this case though, we're not able to disable `napt` *locally* (per `netif`) with the same API.

There's also another API, that checks the `netif`'s number, rather than IP:

https://github.com/espressif/esp-lwip/blob/d5e56d06658ae11292be1baea56204f7120b6fa7/src/core/ipv4/ip4_napt.c#L193-L206

which simply sets `napt` **ON** both globally and locally for the specific interface number.

We've newly added a simple API for enabling and disabling it per interface (not need to lookup based on address, number)

https://github.com/espressif/esp-lwip/blob/280c3d61d9422c570469a21330903762a7727f98/src/core/ipv4/ip4_napt.c#L209

**Comment by david-cermak** [comment]
Closing as this was not a typo, and we've already introduced the new API of `ip_napt_enable_netif()`
